---
- block:

## https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
        
    - name: Add repository for Microsoft ODBC Driver for SQL Server
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/{{ ansible_facts['distribution_version'] }}/prod.list
        dest: /etc/apt/sources.list.d/mssql-release.list
        mode: '0440'  
        
    - name: Update all packages to their latest version
      apt:
        update_cache: yes

    - name: accept license agreement
      ansible.builtin.shell: echo "msodbcsql17 msodbcsql/ACCEPT_EULA boolean true" | debconf-set-selections

# not sure yet if we need this or not
#    - name: accept license agreement
#      ansible.builtin.shell: echo "mssql-tools msodbcsql/ACCEPT_EULA boolean true" | debconf-set-selections

    - name: Install msodbcsql17, unixodbc-dev and mssql-tools
      apt: pkg={{ item }} state=present
      with_items:
        - msodbcsql17
        - unixodbc-dev
        - mssql-tools

    - name: Install sqlsrv and pdo_sqlsrv via pear/pecl
      pear:
        name: pecl/{{ item }}
        state: present
      with_items:
        - sqlsrv
        - pdo_sqlsrv

    - name: Load driver files sqlsrv.so & pdo_sqlsrv.so
      lineinfile:
        path: '/etc/php/{{ mssql_driver_php_version }}/mods-available/{{ item.file }}'
        line: 'extension={{ item.driver }}'
        state: present
        create: yes
      with_items:
        - { file: 'sqlsrv.ini', driver: 'sqlsrv.so' }
        - { file: 'pdo_sqlsrv.ini', driver: 'pdo_sqlsrv.so' }

    - name: Enable the extension for cli and fpm
      file:
        src: '/etc/php/{{ mssql_driver_php_version }}/mods-available/{{ item.src }}'
        dest: '/etc/php/{{ mssql_driver_php_version }}/{{ item.dest }}'
        state: link
      with_items:
        - { src: 'sqlsrv.ini', dest: 'cli/conf.d/20-sqlsrv.ini' }
        - { src: 'pdo_sqlsrv.ini', dest: 'cli/conf.d/20-pdo_sqlsrv.ini' }
        - { src: 'sqlsrv.ini', dest: 'fpm/conf.d/20-sqlsrv.ini' }
        - { src: 'pdo_sqlsrv.ini', dest: 'fpm/conf.d/20-pdo_sqlsrv.ini' }

  become: yes
  become_user: root
